### ISSUE TITLE
Hello, could you open source your training code

### ISSUE THREAD

**Issue by wuxiaolianggit** [pablovela5620/Hand-Detection-and-Distance-Estimation#3]
Hello, could you open source your training code? @pablovela5620

**Comment by pablovela5620** [comment]
Hi, Unfortunately I no longer have it. Though I just used the [Tensorflow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection). Its been updated so even if I did have it, it most likely wouldn't work.

**Comment by wuxiaolianggit** [comment]
Thank you very much for your reply @pablovela5620

**Comment by wuxiaolianggit** [comment]
Could you send a link to your dataset？ @pablovela5620

**Comment by pablovela5620** [comment]
Links to the datasets that I used are in the acknowledgments in the README, specifically vivahands and egohands, though I'm sure that there are some better ones opensource now since its been a while since I made this project
