### ISSUE TITLE
Hello. Could you send a link to your dataset？

### ISSUE THREAD

**Issue by trunghung1410** [pablovela5620/Hand-Detection-and-Distance-Estimation#4]

**Comment by trunghung1410** [comment]
ssd5_optimized_inference_graph.pb

**Comment by pablovela5620** [comment]
Hi trunghung, they are linked in the acknowledgments. Though there are some better ones out there now.  This paper goes over a few hand ones in section 6 https://arxiv.org/pdf/2006.05927.pdf
